### PR TITLE
Use external `prop-types` instead of React.PropTypes

### LINKED ISSUE #16: prop-types
First of all thx for your great work!

The "actual" version 0.3.3-beta unfortunately still uses React.PropTypes, which are removed in actual React 16 beta. Hence react-scroll-box 0.3.3-beta cannot be used with React 16. 

Could you please accept the pull request [https://github.com/smikhalevski/react-scroll-box/pull/15 ](https://github.com/smikhalevski/react-scroll-box/pull/15) or publish a version from you branch v4?

### PR DESCRIPTION
**Pull request by emedvedev**
Fixes #16

Accessing PropTypes via the main React package is deprecated, and will be removed in React v16.0—fairly soon. I've made a very minor update to make sure that this package will keep working even with v16.0. Could you please merge it and publish to npm?

Thank you very much.

### CODE REVIEW

**Comment by dawaa** [comment]
@emedvedev Could you update package.json "dependencies" to be "peerDependencies" instead? Got this error when trying out your PR. 

>  Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

It seems like because of react being under "dependencies" it's being loaded twice.

**Comment by emedvedev** [comment]
@dawaa done :)

**Comment by emedvedev** [comment]
@smikhalevski any chance this PR could be merged? I'd really appreciate it, because I'm using the module in production, but have to install it from my git fork instead of a published npm module, which is, of course, less than ideal.

**Comment by html-krit** [comment]
me too, merge this plz 👍

**Comment by smikhalevski** [comment]
@emedvedev thank you for this pull request! Please remove generated files `target/out/*` from PR, so I can merge it.

**Comment by emedvedev** [comment]
Done :)

**Comment by smikhalevski** [comment]
@emedvedev @html-krit @dawaa Published `react-scroll-box@0.3.5`

**Pull request merged**
